- name: Make artifact directory
    run: mkdir -p ./artifacts/${{ github.repository }}

- name: Create Zip File
    uses: montudor/action-zip@v0.1.0
    with:
    args: zip -r ./artifacts/${{ github.repository }}/${{ github.sha }}.zip ./lambda

- name: Push Lambda Zip to S3
    uses: jakejarvis/s3-sync-action@v0.3.1
    env:
    AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: 'us-east-1'
    SOURCE_DIR: './artifacts'
    DEST_DIR: 'lambda_code'